name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        
    steps:       
    - uses: actions/checkout@v2
        
    - name: Install Ubuntu version
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        make DEBUG=yes
        # sudo apt-get -y install gcc-mingw-w64-i686 gcc
        # make XC=win DEBUG=yes
        # make -C gui XC=win DEBUG=yes

    - name: Install Mac version
      if: matrix.os == 'macOS-latest'
      run: |
        make USE_THREADED_IIN=no DEBUG=yes
        # brew install mingw-w64 gcc make
        # make XC=win DEBUG=yes
        # make -C gui XC=win DEBUG=yes

    - uses: actions/upload-artifact@v2
      with:
        name: rel/hdl_*
        path: hdl-${{matrix.os}}.zip

